import type { CapacitorConfig } from '@capacitor/cli';

// Capacitor wraps the Vite web build (dist/) into a native Android shell. The web build
// is the single source of truth; this file just tells Capacitor where it is and how to
// name the app. `npm run android:sync` rebuilds dist/ and copies it into the android/
// project; `npm run android:open` opens it in Android Studio to produce the APK.
//
// Note: `android/` is generated by `npx cap add android` and is git-ignored — it is a
// build artifact, regenerated from this config + dist/.
const config: CapacitorConfig = {
  appId: 'com.rajdeepsah.speckledband',
  appName: 'The Speckled Band',
  webDir: 'dist',
};

export default config;
